In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('blinkit_customers.csv')

In [3]:
df.head(10)

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
0,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,451.92
1,22077605,Megha Sachar,vedant45@example.com,915123179717,"51/302, Buch Chowk\nSrinagar-570271",Aligarh,149394,2024-06-18,Inactive,4,825.48
2,47822591,Hema Bahri,samiazaan@example.com,910034076149,"941\nAnne Street, Darbhanga 186125",Begusarai,621411,2024-09-25,Regular,17,1969.81
3,79726146,Zaitra Vig,ishanvi87@example.org,916264232390,"43/94, Ghosh, Alappuzha 635655",Kozhikode,826054,2023-10-04,New,4,220.09
4,57102800,Januja Verma,atideshpande@example.org,917293526596,"06\nOm, Ambarnath 477463",Ichalkaranji,730539,2024-03-22,Inactive,14,578.14
5,54748429,Darsh More,ynayar@example.org,912582120513,"26/961\nSalvi Circle, Durg 406361",Visakhapatnam,883122,2024-04-22,New,2,669.35
6,49152878,Patrick Sandhu,zehaanmahajan@example.org,912413014420,"304\nTara Road, Gandhinagar-559930",Gwalior,649817,2024-09-13,Premium,4,973.62
7,16379942,Harshil Kuruvilla,pathakanirudh@example.org,913807361990,"37/62, Basu Chowk\nSikar 515907",Orai,332997,2024-04-10,Inactive,15,1370.56
8,11071601,Ojas Ahuja,sneha11@example.com,912865080618,H.No. 99\nKade Road\nRamgarh 695009,Buxar,528426,2023-07-04,Inactive,17,1950.54
9,68164013,Netra Chander,hwarrior@example.org,917645901970,"H.No. 94\nGupta Path, Hospet-831040",Malegaon,4515,2023-06-29,New,1,1061.82

In [4]:
df.describe(include='all')

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
count,2.500000e+03,2500,2500,2.500000e+03,2500,2500,2500.000000,2500,2500,2500.000000,2500.000000
unique,NaN,2491,2496,NaN,2500,316,NaN,589,4,NaN,NaN
top,NaN,Aarush Ratti,ydevan@example.net,NaN,"H.No. 791, Sur Path\nBally 982559",Jalna,NaN,2024-04-22,Regular,NaN,NaN
freq,NaN,2,2,NaN,1,18,NaN,10,639,NaN,NaN
mean,4.989961e+07,NaN,NaN,9.150532e+11,NaN,NaN,497653.183200,NaN,NaN,10.491600,1102.375836
std,2.919266e+07,NaN,NaN,2.882835e+09,NaN,NaN,281167.293249,NaN,NaN,5.805533,523.043183
min,3.181300e+04,NaN,NaN,9.100132e+11,NaN,NaN,666.000000,NaN,NaN,1.000000,200.430000
25%,2.402443e+07,NaN,NaN,9.125946e+11,NaN,NaN,257079.750000,NaN,NaN,6.000000,631.817500
50%,5.000044e+07,NaN,NaN,9.150236e+11,NaN,NaN,498662.000000,NaN,NaN,10.000000,1118.650000
75%,7.595459e+07,NaN,NaN,9.176256e+11,NaN,NaN,740668.000000,NaN,NaN,16.000000,1565.400000
max,9.989390e+07,NaN,NaN,9.199988e+11,NaN,NaN,999631.000000,NaN,NaN,20.000000,1999.830000

In [5]:
df.dtypes

customer_id            int64
customer_name         object
email                 object
phone                  int64
address               object
area                  object
pincode                int64
registration_date     object
customer_segment      object
total_orders           int64
avg_order_value      float64
dtype: object

In [6]:
df['registration_date']=pd.to_datetime(df['registration_date'])

In [7]:
df.isnull().sum()

customer_id          0
customer_name        0
email                0
phone                0
address              0
area                 0
pincode              0
registration_date    0
customer_segment     0
total_orders         0
avg_order_value      0
dtype: int64

In [8]:
print(df.duplicated().sum())
print(df['customer_id'].duplicated().sum())

0
0

In [9]:
df.shape

(2500, 11)

In [10]:
df1=pd.read_csv('blinkit_customer_feedback.csv')
df2=pd.read_csv('blinkit_delivery_performance.csv')

In [11]:
df1.head(10)

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
0,2234710,1961864118,30065862,4,"It was okay, nothing special.",Delivery,Neutral,2024-07-17
1,5450964,1549769649,9573071,3,The order was incorrect.,App Experience,Negative,2024-05-28
2,482108,9185164487,45477575,3,"It was okay, nothing special.",App Experience,Neutral,2024-09-23
3,4823104,9644738826,88067569,4,The product met my expectations.,App Experience,Neutral,2023-11-24
4,3537464,5427684290,83298567,3,Product was damaged during delivery.,Delivery,Negative,2023-11-20
5,4089724,3265154092,43367112,2,Product was damaged during delivery.,Customer Service,Negative,2023-03-18
6,230696,4898355547,13284996,4,Highly recommended!,Product Quality,Positive,2023-04-16
7,2259308,6568151549,88866835,2,I had a bad experience.,App Experience,Negative,2024-03-31
8,7380970,6006693867,24496983,3,Product was damaged during delivery.,Delivery,Negative,2023-07-14
9,2257242,374186990,52215833,3,The product met my expectations.,App Experience,Neutral,2023-08-09

In [12]:
df1.describe(include='all')

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
count,5.000000e+03,5.000000e+03,5.000000e+03,5000.00000,5000,5000,5000,5000
unique,NaN,NaN,NaN,NaN,25,4,3,600
top,NaN,NaN,NaN,NaN,The product met my expectations.,Delivery,Neutral,2024-09-10
freq,NaN,NaN,NaN,NaN,386,1271,1738,17
mean,5.013616e+06,5.029129e+09,5.009685e+07,3.34440,NaN,NaN,NaN,NaN
std,2.857341e+06,2.863533e+09,2.919082e+07,1.18982,NaN,NaN,NaN,NaN
min,9.470000e+02,6.046500e+04,3.181300e+04,1.00000,NaN,NaN,NaN,NaN
25%,2.576690e+06,2.531421e+09,2.404314e+07,3.00000,NaN,NaN,NaN,NaN
50%,5.005833e+06,5.074378e+09,4.997808e+07,4.00000,NaN,NaN,NaN,NaN
75%,7.486478e+06,7.488579e+09,7.621215e+07,4.00000,NaN,NaN,NaN,NaN
max,9.999293e+06,9.998298e+09,9.989390e+07,5.00000,NaN,NaN,NaN,NaN

In [13]:
df1.dtypes

feedback_id           int64
order_id              int64
customer_id           int64
rating                int64
feedback_text        object
feedback_category    object
sentiment            object
feedback_date        object
dtype: object

In [14]:
df1['feedback_date']=pd.to_datetime(df1['feedback_date'])

In [15]:
df1.isnull().sum()

feedback_id          0
order_id             0
customer_id          0
rating               0
feedback_text        0
feedback_category    0
sentiment            0
feedback_date        0
dtype: int64

In [16]:
print(df1.duplicated().sum())
print(df1['customer_id'].duplicated().sum())
print(df1['feedback_id'].duplicated().sum())
print(df1['order_id'].duplicated().sum())

0
2828
0
0

In [17]:
df1.shape

(5000, 8)

In [18]:
df2.head(10)

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,NaN
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,NaN
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic
5,3265154092,554,2023-03-18 16:49:51,2023-03-18 16:48:51,-1.0,1.94,On Time,NaN
6,4898355547,14630,2023-04-16 19:01:37,2023-04-16 19:02:37,1.0,2.20,On Time,Traffic
7,6568151549,67714,2024-03-31 06:37:48,2024-03-31 06:39:48,2.0,1.30,On Time,Traffic
8,6006693867,91362,2023-07-14 00:02:36,2023-07-14 00:05:36,3.0,3.38,On Time,Traffic
9,374186990,77203,2023-08-09 01:37:30,2023-08-09 01:44:30,7.0,1.47,Slightly Delayed,Traffic

In [19]:
df2.describe(include='all')

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
count,5.000000e+03,5000.000000,5000,5000,5000.000000,5000.000000,5000,3098
unique,NaN,NaN,4999,5000,NaN,NaN,3,1
top,NaN,NaN,2024-10-13 14:06:50,2023-08-23 12:21:18,NaN,NaN,On Time,Traffic
freq,NaN,NaN,2,1,NaN,NaN,3470,3098
mean,5.029129e+09,50050.318200,NaN,NaN,4.443000,2.718048,NaN,NaN
std,2.863533e+09,28802.276922,NaN,NaN,8.063929,1.290306,NaN,NaN
min,6.046500e+04,43.000000,NaN,NaN,-5.000000,0.500000,NaN,NaN
25%,2.531421e+09,24928.500000,NaN,NaN,-1.000000,1.590000,NaN,NaN
50%,5.074378e+09,50262.500000,NaN,NaN,2.000000,2.690000,NaN,NaN
75%,7.488579e+09,74478.250000,NaN,NaN,8.000000,3.850000,NaN,NaN
max,9.998298e+09,99968.000000,NaN,NaN,30.000000,5.000000,NaN,NaN

In [20]:
df2.dtypes

order_id                   int64
delivery_partner_id        int64
promised_time             object
actual_time               object
delivery_time_minutes    float64
distance_km              float64
delivery_status           object
reasons_if_delayed        object
dtype: object

In [21]:
df2['promised_time']=pd.to_datetime(df2['promised_time'])
df2['actual_time']=pd.to_datetime(df2['actual_time'])

In [22]:
df2.isnull().sum()

order_id                    0
delivery_partner_id         0
promised_time               0
actual_time                 0
delivery_time_minutes       0
distance_km                 0
delivery_status             0
reasons_if_delayed       1902
dtype: int64

In [23]:
print(df2.duplicated().sum())
print(df2['order_id'].duplicated().sum())
print(df2['delivery_partner_id'].duplicated().sum())

0
0
0

In [24]:
df2.shape

(5000, 8)

In [25]:
common_customer_ids = df1[df1['customer_id'].isin(df['customer_id'])]['customer_id'].unique()
print(f"Number of common customer IDs between df and df1: {len(common_customer_ids)}")

Number of common customer IDs between df and df1: 2172

In [26]:
print(df['customer_id'].nunique())
print(df1['customer_id'].nunique())
print(len(common_customer_ids))

2500
2172
2172

In [27]:
from numpy import isin
common_order_ids=df2[df2['order_id'].isin(df1['order_id'])]['order_id'].unique()
print(f'number of common order id between df2 and df3:{len(common_order_ids)}')

number of common order id between df2 and df3:5000

In [28]:
print(df1['order_id'].nunique())
print(df2['order_id'].nunique())
print(len(common_order_ids))

5000
5000
5000

In [29]:
order=pd.read_csv('blinkit_orders.csv')

In [30]:
order.head(10)

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741
5,3265154092,43367112,2023-03-18 16:29:51,2023-03-18 16:49:51,2023-03-18 16:48:51,On Time,3161.43,UPI,554,3442
6,4898355547,13284996,2023-04-16 18:50:37,2023-04-16 19:01:37,2023-04-16 19:02:37,On Time,956.40,Card,14630,1318
7,6568151549,88866835,2024-03-31 06:26:48,2024-03-31 06:37:48,2024-03-31 06:39:48,On Time,905.47,Cash,67714,115
8,6006693867,24496983,2023-07-13 23:49:36,2023-07-14 00:02:36,2023-07-14 00:05:36,On Time,1371.17,Card,91362,9021
9,374186990,52215833,2023-08-09 01:17:30,2023-08-09 01:37:30,2023-08-09 01:44:30,Slightly Delayed,1601.19,Wallet,77203,7955

In [31]:
order.describe(include='all')

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
count,5.000000e+03,5.000000e+03,5000,5000,5000,5000,5000.00000,5000,5000.000000,5000.000000
unique,NaN,NaN,5000,4999,5000,3,NaN,4,NaN,NaN
top,NaN,NaN,2023-08-23 12:04:18,2024-10-13 14:06:50,2023-08-23 12:21:18,On Time,NaN,Card,NaN,NaN
freq,NaN,NaN,1,2,1,3470,NaN,1285,NaN,NaN
mean,5.029129e+09,5.009685e+07,NaN,NaN,NaN,NaN,2201.86170,NaN,50050.318200,4999.689000
std,2.863533e+09,2.919082e+07,NaN,NaN,NaN,NaN,1303.02438,NaN,28802.276922,2886.089242
min,6.046500e+04,3.181300e+04,NaN,NaN,NaN,NaN,13.25000,NaN,43.000000,1.000000
25%,2.531421e+09,2.404314e+07,NaN,NaN,NaN,NaN,1086.21500,NaN,24928.500000,2509.250000
50%,5.074378e+09,4.997808e+07,NaN,NaN,NaN,NaN,2100.69000,NaN,50262.500000,4987.000000
75%,7.488579e+09,7.621215e+07,NaN,NaN,NaN,NaN,3156.88250,NaN,74478.250000,7500.750000
max,9.998298e+09,9.989390e+07,NaN,NaN,NaN,NaN,6721.46000,NaN,99968.000000,9995.000000

In [32]:
order.dtypes

order_id                    int64
customer_id                 int64
order_date                 object
promised_delivery_time     object
actual_delivery_time       object
delivery_status            object
order_total               float64
payment_method             object
delivery_partner_id         int64
store_id                    int64
dtype: object

In [33]:
order['order_date']=pd.to_datetime(order['order_date'])
order['actual_delivery_time']=pd.to_datetime(order['actual_delivery_time'])
order['promised_delivery_time']=pd.to_datetime(order['promised_delivery_time'])

In [34]:
order.isnull().sum()

order_id                  0
customer_id               0
order_date                0
promised_delivery_time    0
actual_delivery_time      0
delivery_status           0
order_total               0
payment_method            0
delivery_partner_id       0
store_id                  0
dtype: int64

In [35]:
print(order.duplicated().sum())
print(order['order_id'].duplicated().sum())
print(order['customer_id'].duplicated().sum())
print(order['delivery_partner_id'].duplicated().sum())

0
0
2828
0

In [36]:
order.shape

(5000, 10)

In [37]:
order_item=pd.read_csv('blinkit_order_items.csv')

In [38]:
order_item.head(10)

     order_id  product_id  quantity  unit_price
0  1961864118      642612         3      517.03
1  1549769649      378676         1      881.42
2  9185164487      741341         2      923.84
3  9644738826      561860         1      874.78
4  5427684290      602241         2      976.55
5  3265154092      681063         1      321.28
6  4898355547       56589         3      517.77
7  6568151549      500739         2      359.98
8  6006693867      490939         1       80.25
9   374186990      760828         2      563.45

In [39]:
order_item.describe(include='all')

           order_id     product_id     quantity   unit_price
count  5.000000e+03    5000.000000  5000.000000  5000.000000
mean   5.029129e+09  509974.939600     2.006800   493.157900
std    2.863533e+09  293678.307475     0.820542   298.075647
min    6.046500e+04    4452.000000     1.000000    12.320000
25%    2.531421e+09  257719.000000     1.000000   227.220000
50%    5.074378e+09  540618.000000     2.000000   448.160000
75%    7.488579e+09  747801.000000     3.000000   781.080000
max    9.998298e+09  993331.000000     3.000000   995.980000

In [40]:
order_item.dtypes

order_id        int64
product_id      int64
quantity        int64
unit_price    float64
dtype: object

In [41]:
print(order_item.duplicated().sum())
print(order_item['order_id'].duplicated().sum())
print(order_item['product_id'].duplicated().sum())

0
0
4732

In [42]:
order_item['revenue']=order_item['unit_price']*order_item['quantity']

In [43]:
order_item.head(10)

     order_id  product_id  quantity  unit_price  revenue
0  1961864118      642612         3      517.03  1551.09
1  1549769649      378676         1      881.42   881.42
2  9185164487      741341         2      923.84  1847.68
3  9644738826      561860         1      874.78   874.78
4  5427684290      602241         2      976.55  1953.10
5  3265154092      681063         1      321.28   321.28
6  4898355547       56589         3      517.77  1553.31
7  6568151549      500739         2      359.98   719.96
8  6006693867      490939         1       80.25    80.25
9   374186990      760828         2      563.45  1126.90

In [44]:
order_item.shape

(5000, 5)

In [45]:
market_perf=pd.read_csv('blinkit_marketing_performance.csv')

In [46]:
market_perf.head(10)

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
0,548299,New User Discount,2024-11-05,Premium,App,3130,163,78,1431.85,4777.75,3.60
1,390914,Weekend Special,2024-11-05,Inactive,App,3925,494,45,4506.34,6238.11,2.98
2,834385,Festival Offer,2024-11-05,Inactive,Email,7012,370,78,4524.23,2621.00,2.95
3,241523,Flash Sale,2024-11-05,Inactive,SMS,1115,579,86,3622.79,2955.00,2.84
4,595111,Membership Drive,2024-11-05,New Users,Email,7172,795,54,2888.99,8951.81,2.22
5,176344,Category Promotion,2024-11-05,Inactive,App,4333,421,40,2714.78,6697.88,3.89
6,875646,App Push Notification,2024-11-05,Premium,Email,4752,937,21,3584.76,9152.99,2.14
7,5516,Email Campaign,2024-11-05,Premium,Social Media,1559,418,68,1457.88,2156.09,3.92
8,989534,Referral Program,2024-11-05,New Users,SMS,3838,911,45,4808.64,8074.17,1.70
9,243346,New User Discount,2024-11-04,Inactive,SMS,6289,834,14,3746.35,4474.02,2.56

In [47]:
market_perf.describe(include='all')

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
count,5400.000000,5400,5400,5400,5400,5400.000000,5400.000000,5400.000000,5400.000000,5400.000000,5400.000000
unique,NaN,9,600,4,4,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,New User Discount,2023-03-17,New Users,App,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,600,9,1356,1374,NaN,NaN,NaN,NaN,NaN,NaN
mean,501315.219074,NaN,NaN,NaN,NaN,5460.668519,550.767593,55.192222,3022.192267,5961.742106,2.740711
std,287611.524258,NaN,NaN,NaN,NaN,2571.779820,260.080051,26.150173,1148.732680,2322.242911,0.722986
min,243.000000,NaN,NaN,NaN,NaN,1002.000000,100.000000,10.000000,1000.630000,2003.100000,1.500000
25%,249200.000000,NaN,NaN,NaN,NaN,3231.500000,322.000000,32.000000,2029.070000,3907.240000,2.120000
50%,505012.500000,NaN,NaN,NaN,NaN,5457.500000,555.000000,55.000000,3042.485000,5935.940000,2.725000
75%,752219.250000,NaN,NaN,NaN,NaN,7676.250000,772.000000,78.000000,4011.572500,7973.712500,3.370000
max,999950.000000,NaN,NaN,NaN,NaN,9999.000000,1000.000000,100.000000,4997.550000,9999.540000,4.000000

In [48]:
market_perf.dtypes

campaign_id            int64
campaign_name         object
date                  object
target_audience       object
channel               object
impressions            int64
clicks                 int64
conversions            int64
spend                float64
revenue_generated    float64
roas                 float64
dtype: object

In [49]:
market_perf['date']=pd.to_datetime(market_perf['date'])

In [50]:
market_perf.isnull().sum()

campaign_id          0
campaign_name        0
date                 0
target_audience      0
channel              0
impressions          0
clicks               0
conversions          0
spend                0
revenue_generated    0
roas                 0
dtype: int64

In [51]:
print(market_perf.duplicated().sum())
print(market_perf['campaign_id'].duplicated().sum())

0
0

In [52]:
market_perf.shape

(5400, 11)

In [53]:
inv=pd.read_csv('blinkit_inventory.csv')
inv.head(10)

   product_id        date  stock_received  damaged_stock
0      153019  17-03-2023               4              2
1      848226  17-03-2023               4              2
2      965755  17-03-2023               1              0
3       39154  17-03-2023               4              0
4       34186  17-03-2023               3              2
5      478531  17-03-2023               4              2
6      812607  17-03-2023               4              0
7      818990  17-03-2023               4              0
8       14145  17-03-2023               0              2
9      847349  17-03-2023               0              2

In [54]:
inv.describe(include='all')

           product_id        date  stock_received  damaged_stock
count    75172.000000       75172    75172.000000   75172.000000
unique            NaN         600             NaN            NaN
top               NaN  04-06-2023             NaN            NaN
freq              NaN         150             NaN            NaN
mean    514290.353097         NaN        1.962513       1.067791
std     291277.971875         NaN        1.639961       0.997706
min       4452.000000         NaN        0.000000       0.000000
25%     272170.000000         NaN        0.000000       0.000000
50%     542300.000000         NaN        3.000000       2.000000
75%     753354.000000         NaN        3.000000       2.000000
max     993331.000000         NaN        4.000000       2.000000

In [55]:
inv.dtypes

product_id         int64
date              object
stock_received     int64
damaged_stock      int64
dtype: object

In [56]:
inv['date']=pd.to_datetime(inv['date'],dayfirst=True)

In [57]:
inv.isnull().sum()

product_id        0
date              0
stock_received    0
damaged_stock     0
dtype: int64

In [58]:
print(inv.duplicated().sum())
print(inv['product_id'].duplicated().sum())

0
74904

In [59]:
inv.shape

(75172, 4)

In [60]:
inv_new=pd.read_csv('blinkit_inventoryNew.csv')
inv_new.head(10)

   product_id    date  stock_received  damaged_stock
0      153019  Mar-23               4              1
1      848226  Mar-23               4              1
2      965755  Mar-23               1              0
3       39154  Mar-23               4              0
4       34186  Mar-23               3              1
5      478531  Mar-23               4              1
6      812607  Mar-23               4              0
7      818990  Mar-23               4              0
8      284460  Mar-23               4              0
9      654297  Mar-23               4              1

In [61]:
inv_new.describe(include='all')

           product_id    date  stock_received  damaged_stock
count    18105.000000   18105    18105.000000   18105.000000
unique            NaN      21             NaN            NaN
top               NaN  Jul-23             NaN            NaN
freq              NaN    1076             NaN            NaN
mean    514273.410163     NaN        1.589561       0.061254
std     290295.868498     NaN        0.797942       0.265387
min       4452.000000     NaN        1.000000       0.000000
25%     274207.000000     NaN        1.000000       0.000000
50%     540618.000000     NaN        1.000000       0.000000
75%     753354.000000     NaN        2.000000       0.000000
max     993331.000000     NaN        4.000000       7.000000

In [62]:
inv_new.dtypes

product_id         int64
date              object
stock_received     int64
damaged_stock      int64
dtype: object

In [63]:
order_item.groupby('product_id')['unit_price'].nunique().sort_values(ascending=False)

product_id
993331    1
4452      1
6405      1
9436      1
11422     1
         ..
52729     1
51036     1
41853     1
39154     1
36412     1
Name: unit_price, Length: 268, dtype: int64

In [64]:
product=pd.read_csv('blinkit_products.csv')
product.head(10)

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,153019,Onions,Fruits & Vegetables,Aurora LLC,947.95,1263.93,25.0,3,13,88
1,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65
2,669378,Potatoes,Fruits & Vegetables,Chadha and Sons,212.14,282.85,25.0,3,23,70
3,848226,Tomatoes,Fruits & Vegetables,Barad and Sons,209.59,279.45,25.0,3,10,51
4,890623,Onions,Fruits & Vegetables,"Sangha, Nagar and Varty",354.52,472.69,25.0,3,27,55
5,965755,Bananas,Fruits & Vegetables,"Doshi, Sarraf and Sama",532.57,710.09,25.0,3,21,91
6,222892,Tomatoes,Fruits & Vegetables,Ramakrishnan-Ghose,869.22,1158.96,25.0,3,28,88
7,516376,Onions,Fruits & Vegetables,Agarwal-Dhar,877.43,1169.91,25.0,3,21,71
8,39154,Mangoes,Fruits & Vegetables,"Suresh, Bose and Bajwa",946.86,1262.48,25.0,3,21,84
9,34186,Mangoes,Fruits & Vegetables,Mandal-Kar,925.65,1234.20,25.0,3,27,74

In [65]:
product.describe(include='all')

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
count,268.000000,268,268,268,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000
unique,NaN,51,11,267,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Pet Treats,Dairy & Breakfast,Jha Group,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,12,30,2,NaN,NaN,NaN,NaN,NaN,NaN
mean,514855.940299,NaN,NaN,NaN,488.356828,680.434739,27.779851,231.757463,20.388060,74.753731
std,291391.529820,NaN,NaN,NaN,298.487200,419.772224,7.458753,151.205830,5.958546,14.591535
min,4452.000000,NaN,NaN,NaN,12.320000,17.600000,15.000000,3.000000,10.000000,50.000000
25%,273697.750000,NaN,NaN,NaN,226.717500,325.150000,20.000000,90.000000,15.000000,63.750000
50%,541459.000000,NaN,NaN,NaN,442.185000,616.970000,30.000000,365.000000,21.000000,73.000000
75%,754334.000000,NaN,NaN,NaN,779.445000,1056.620000,35.000000,365.000000,25.250000,88.000000
max,993331.000000,NaN,NaN,NaN,995.980000,1633.320000,40.000000,365.000000,30.000000,100.000000

In [66]:
product.dtypes

product_id             int64
product_name          object
category              object
brand                 object
price                float64
mrp                  float64
margin_percentage    float64
shelf_life_days        int64
min_stock_level        int64
max_stock_level        int64
dtype: object

In [67]:
product.isnull().sum()

product_id           0
product_name         0
category             0
brand                0
price                0
mrp                  0
margin_percentage    0
shelf_life_days      0
min_stock_level      0
max_stock_level      0
dtype: int64

In [68]:
print(product.duplicated().sum())
print(product['product_id'].duplicated().sum())

0
0

In [69]:
product['discount']=product['mrp']-product['price']
product['discount_percentage']=(product['discount']/product['mrp'])*100

In [70]:
product.head(10)

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level,discount,discount_percentage
0,153019,Onions,Fruits & Vegetables,Aurora LLC,947.95,1263.93,25.0,3,13,88,315.98,24.999802
1,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65,42.39,25.001474
2,669378,Potatoes,Fruits & Vegetables,Chadha and Sons,212.14,282.85,25.0,3,23,70,70.71,24.999116
3,848226,Tomatoes,Fruits & Vegetables,Barad and Sons,209.59,279.45,25.0,3,10,51,69.86,24.999105
4,890623,Onions,Fruits & Vegetables,"Sangha, Nagar and Varty",354.52,472.69,25.0,3,27,55,118.17,24.999471
5,965755,Bananas,Fruits & Vegetables,"Doshi, Sarraf and Sama",532.57,710.09,25.0,3,21,91,177.52,24.999648
6,222892,Tomatoes,Fruits & Vegetables,Ramakrishnan-Ghose,869.22,1158.96,25.0,3,28,88,289.74,25.000000
7,516376,Onions,Fruits & Vegetables,Agarwal-Dhar,877.43,1169.91,25.0,3,21,71,292.48,25.000214
8,39154,Mangoes,Fruits & Vegetables,"Suresh, Bose and Bajwa",946.86,1262.48,25.0,3,21,84,315.62,25.000000
9,34186,Mangoes,Fruits & Vegetables,Mandal-Kar,925.65,1234.20,25.0,3,27,74,308.55,25.000000

In [71]:
product.shape

(268, 12)

In [77]:
from numpy._core.fromnumeric import prod
order.to_csv("cleaned_orders.csv", index=False)

df.to_csv("cleaned_customers.csv", index=False)

df1.to_csv("cleaned_customer_feedback.csv", index=False)
order_item.to_csv("cleaned_order_item.csv", index=False)
market_perf.to_csv("cleaned_market_performance.csv", index=False)
df2.to_csv("cleaned_delivery_perf.csv", index=False)

inv.to_csv("cleaned_inventory.csv", index=False)

inv_new.to_csv("cleaned_inventoryNew.csv", index=False)
product.to_csv("product_cleaned.csv", index=False)